import React, { useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import './ContentGuide.css'; // Reusing the same CSS

const About = ({ isOpen, toggleAbout }) => {

  useEffect(() => {
    if (!isOpen) return;

    const handleOutsideClick = (e) => {
      if (e.target.className === 'content-guide-popup') {
        toggleAbout();
      }
    };

    // Add event listener to close about page when clicking outside of the content box
    document.addEventListener('mousedown', handleOutsideClick);

    // Clean up event listener when component is unmounted or isOpen changes
    return () => {
      document.removeEventListener('mousedown', handleOutsideClick);
    };
  }, [isOpen, toggleAbout]);

  if (!isOpen) return null;

  return (
    <div className="content-guide-popup">
      <div className="content-guide-content">
        <h1>About this game...</h1>
        <p>
          This is a VERY early beta version of an interactive educational game created by <a href="https://benjaminpbreen.com"> Benjamin Breen </a>  in Summer, 2024. It immerses you in the life of a 17th-century apothecary in colonial Mexico City. The "playable character" is based on a real person, Maria Coelho. It is a first draft of a larger educational game platform, HistoryLens, aimed at undergraduate students which I am curently working on. 
<br /><br />
          It grew out of early experiments with using ChatGPT as a tool for creating naive, imperfect simulations of the past - the simulations ALWAYS broke or had significant issues, but I found these issues to be, themselves, richly instructive and interesting. It is important to see this platform as part of a larger learning experience which is intended to be a jumping-off point for further research and reading into the real histories - not an ending, but a beginning. 
          <br /><br />
          The goal is to immerse you in a different world, but also to get you to think about the nature of AI systems and historical evidence, and the imperfections of both. 
        </p>

        The content is based directly on research into early modern apothecaries I conducted for my PhD dissertation at UT Austin, some of which is included in my first book, <em> The Age of Intoxication: Origins of the Global Drug Trade </em> (University of Pennsylvania Press, 2019).

                <br /><br />
        
        <h2>Overview</h2>
        <p>
          HistoryLens is an LLM-powered historical role-playing/simulation that relies on player input to proceed. You can type any command into the input box, or try specific commands like:
          #prescribe, #map, #buy, #diagnose, or #symptoms. 

          <br /><br />

          Improvise, be playful, and experiment with the limits of the simulated world. Maria need not stay in her home or treat patients. She can try to leave Mexico City, she search for new materia medica, she can reflect on her past. The engine allows players to make unique, personalized decisions with dynamic consequences. 
<br /><br />
          Don't forget to experiment with the "Mix Drugs" panel - the most interesting part of the game IMO! 

          Although it the main "output" is generated by an AI, the game is grounded in primary sources and academic research. You can click the "Counter-Narrative" button to get specific historical details and fact-checking about any "turn" of the game, and can even click the "Incorporate" button to weave that back into the main narrative. 
        </p>
     

        <h2>Tips & Help</h2>
        <ul>
          <li><strong>Explore Thoroughly:</strong> Interact with different elements in the game to uncover hidden details and understand the broader historical context.</li>
          <li><strong>Use the Counter-Narrative:</strong> The "Counter-Narrative" button offers an alternative perspective on the events in the simulation.</li>
          <li><strong>Mixing and Prescribing:</strong> Pay attention to the historical accuracy of the ingredients when mixing and prescribing. The game will evaluate your choices based on period-appropriate knowledge.</li>
    <br />
          Don't forget that you can simply type #help or "give me some advice" into the input box. 
        </ul>
         <br />

        <h2>Further Reading</h2>
        <p> 

        To get the most out of this game, you need to play it alongside serious reading in the history of medicine in the seventeenth century -- a richly studied field and a fascinatingly weird chapter of history. 

        Here are some recommended readings:</p>
        <ul>
       <li><strong>Paula De Vos</strong>. <em>From Herbs to Alchemy: The Introduction of Chemical Medicine to Mexican Pharmacies in the Seventeenth and Eighteenth Centuries</em>. Journal of Spanish Cultural Studies, 2007. <a href="https://www.tandfonline.com/doi/full/10.1080/14636200701430984">DOI link</a></li>
          <li><strong>LA Newson</strong>. <em>Making Medicines in Early Colonial Lima, Peru: Apothecaries, Science and Society</em>. 2017. </li>
          <li><strong>Pablo F. Gómez</strong>. <em>The Experiential Caribbean: Creating Knowledge and Healing in the Early Modern Atlantic</em>. Chapel Hill: University of North Carolina Press, 2017.</li>
          <li><strong>Daniela Bleichmar</strong>. <em>Visible Empire: Botanical Expeditions and Visual Culture in the Hispanic Enlightenment</em>. Chicago: University of Chicago Press, 2012. </li>
          <li><strong>Matthew Crawford</strong>. <em>The Andean Wonder Drug: Cinchona Bark and Imperial Science in the Spanish Atlantic, 1630-1800</em>. Pittsburgh: University of Pittsburgh Press, 2016. </li>

<br />
          Additionally, if you're interested in educational simulation games, I first explored this game idea in depth here: <a href="https://resobscura.substack.com/p/llm-based-educational-games-will">here.</a>. 
        </ul>  <br />
        <h2>About the creator</h2>
        <p>
          HistoryLens was created by Benjamin Breen (see the Colophon for more info). I am a historian and writer focused on the history of science, medicine, technology, and globalization and an associate professor at UC Santa Cruz. This application is an outgrowth of an ongoing collaboration with Pranav Anand and Zac Zimmer at UCSC. 
        </p>

        <h2>Contact & Collaboration</h2>
        <p>
         Feel free to reach out at <a href="mailto:bebreen@ucsc.edu">bebreen@ucsc.edu</a>.
        </p>
        
         <br />
        <button className="close-content-guide-button" onClick={toggleAbout}>Close</button>
      </div>
    </div>
  );
};

export default About;
