const imageMap = {
  anamariadesoto: require('./assets/anamariadesoto.jpg'),
  apothecary: require('./assets/apothecary.jpeg'),
  franciscodiasdearaujo: require('./assets/franciscodiasdearaujo.jpg'),
  carlosenriquez: require('./assets/carlosenriquez.jpg'),
  country: require('./assets/country.jpeg'),
  default: require('./assets/default.jpeg'),
  donalejandrocortez: require('./assets/donalejandrocortez.jpg'),
  donluis: require('./assets/donluis.jpeg'),
  frayesteban: require('./assets/frayesteban.jpg'),
  generichome: require('./assets/generichome.jpeg'),
  inquisitorfernando: require('./assets/inquisitorfernando.jpg'),
  isabeldelacruz: require('./assets/isabeldelacruz.jpg'),
  joao: require('./assets/joao.jpeg'),
  juanbraga: require('./assets/juanbraga.jpg'),
  mariacoelho: require('./assets/mariacoelho.jpeg'),
  market: require('./assets/market.jpeg'),
  marta: require('./assets/marta.jpeg'),
  outsideday: require('./assets/outsideday.jpg'),
  outsidenight: require('./assets/outsidenight.jpg'),
  rosamariaperez: require('./assets/rosamariaperez.jpg'),
  shopmorning: require('./assets/shopmorning.jpeg'),
  shopafternoon: require('./assets/shopafternoon.jpeg'),
  shopnight: require('./assets/shopnight.jpeg'),
  genericfemalecommoner: require('./assets/genericfemalecommoner.jpeg'),
  genericmalecommoner: require('./assets/genericmalecommoner.jpeg'),
  genericfemaleupper: require('./assets/genericfemaleupper.jpeg'),
  genericmaleupper: require('./assets/genericmaleupper.jpeg'),
  manual: require('./assets/manual.jpeg'),
  diegoperez: require('./assets/diegoperez.jpg'),
  mushroom: require('./assets/mushroom.jpeg'),
  study: require('./assets/study.jpeg'),
  farm: require('./assets/farm.jpeg'),
  merchant: require('./assets/merchant.jpeg'),
  street: require('./assets/street.jpeg'),
  codex: require('./assets/codex.jpg'),
  trippy: require('./assets/trippy.jpeg'),
  herbs: require('./assets/herbs.jpeg'),
  herbalist: require('./assets/herbalist.jpeg'),
  priest: require('./assets/priest.jpeg'),
  franciscohernandez: require('./assets/franciscoramirez.jpg'),
  franciscoramirez: require('./assets/franciscoramirez.jpg'),
  cityday: require('./assets/city_day.jpg'),
  streetnight: require('./assets/street_night.jpg'),
  donignaciodemendoza: require('./assets/donignaciodemendoza.jpg'),
  symptoms: require('./assets/symptoms.jpg'),
  tlacaelel: require('./assets/tlacaelel.jpg'),


  // Quest images
  quest0a: require('./assets/quest0a.jpg'),
  quest0b: require('./assets/quest0b.jpg'),
  quest0c: require('./assets/quest0c.jpg'),
  quest0d: require('./assets/quest0d.jpg'),
  quest1a: require('./assets/quest1a.jpg'),
  quest1b: require('./assets/quest1b.jpg'),
  quest1c: require('./assets/quest1c.jpg'),
  quest1d: require('./assets/quest1d.jpg'),
  quest2a: require('./assets/quest2a.jpg'),
  quest2b: require('./assets/quest2b.jpg'),
  quest2c: require('./assets/quest2c.jpg'),
  quest2d: require('./assets/quest2d.jpg'),
  quest3a: require('./assets/quest3a.jpg'),
  quest3b: require('./assets/quest3b.jpg'),
  quest3c: require('./assets/quest3c.jpg'),
  quest3d: require('./assets/quest3d.jpg'),
  quest4a: require('./assets/quest4a.jpg'),
  quest4b: require('./assets/quest4b.jpg'),
  quest4c: require('./assets/quest4c.jpg'),
  quest4d: require('./assets/quest4d.jpg'),
};

export default imageMap;
