// imageMap.js
const imageMap = {
  anamariadesoto: require('./assets/anamariadesoto.jpeg'),
  apothecary: require('./assets/apothecary.jpeg'),
  araujo: require('./assets/araujo.jpeg'),
  carlosenriquez: require('./assets/carlosenriquez.jpeg'),
  country: require('./assets/country.jpeg'),
  default: require('./assets/default.jpeg'),
  donalejandrocortez: require('./assets/donalejandrocortez.jpeg'),
  donluis: require('./assets/donluis.jpeg'),
  frayesteban: require('./assets/frayesteban.jpeg'),
  generichome: require('./assets/generichome.jpeg'),
  inquisitorfernando: require('./assets/inquisitorfernando.jpeg'),
  isabel: require('./assets/isabel.jpeg'),
  joao: require('./assets/joao.jpeg'),
  juan: require('./assets/juan.jpeg'),
  mariacoelho: require('./assets/mariacoelho.jpeg'),
  market: require('./assets/market.jpeg'),
  marta: require('./assets/marta.jpeg'),
  outsideday: require('./assets/outsideday.jpeg'),
  outsidenight: require('./assets/outsidenight.jpeg'),
  rosa: require('./assets/rosa.jpeg'),
  shopmorning: require('./assets/shopmorning.jpeg'),
  shopafternoon: require('./assets/shopafternoon.jpeg'),
  shopnight: require('./assets/shopnight.jpeg'),
  genericfemalecommoner: require('./assets/genericfemalecommoner.jpeg'),
   genericmalecommoner: require('./assets/genericmalecommoner.jpeg'),
 genericfemaleupper: require('./assets/genericfemaleupper.jpeg'),
  genericmaleupper: require('./assets/genericmaleupper.jpeg'),
  manual: require('./assets/manual.jpeg'),
  diegoperez: require('./assets/diegoperez.jpeg'),
  mushroom: require ('./assets/mushroom.jpeg'),
  study: require ('./assets/study.jpeg'),
  farm: require ('./assets/farm.jpeg'),
  merchant: require ('./assets/merchant.jpeg'),
  street: require ('./assets/street.jpeg'),
  codex: require ('./assets/codex.jpeg'),
    trippy: require ('./assets/trippy.jpeg'),
    herbs: require ('./assets/herbs.jpeg'),
    herbalist: require ('./assets/herbalist.jpeg'),
        herbs: require ('./assets/herbs.jpeg'),
        priest: require ('./assets/priest.jpeg'),
};

export default imageMap;
